#!/bin/sh

set -e

lb config noauto \
     -d bookworm \
     --archive-areas "main contrib non-free-firmware" \
     --debian-installer live \
     --debian-installer-distribution bookworm \
     --debian-installer-gui false \
     "${@}"


